### ISSUE TITLE
Make minimum log level configurable

### ISSUE THREAD

**Issue by maertsen** [dave92082/SolarEdge-Exporter#6]
Thanks for writing this exporter. I've just set it up and noticed that the debug level logging is less useful to me.
Would you be open to making the minimum log level configurable? Something like https://github.com/rs/zerolog#setting-global-log-level

For me personally, I think info could be a good default value, though I wouldn't mind configuring it explicitly.

**Comment by dave92082** [comment]
@maertsen, completely agree about the log level. Should be simple to make it configurable and will try to make the change today
