### ISSUE TITLE
Issues connecting to Solaredge SE3000 HD Wave

### ISSUE THREAD

**Issue by 33Fraise33** [dave92082/SolarEdge-Exporter#8]
Hello,

When running the provided software I get the following issue: 

```
8:29AM INF Starting SolarEdge-Exporter
8:29AM INF Configured Inverter Address:
8:29AM INF Configured Inverter Address: 0
8:29AM ERR Error connecting to Inverter: dial tcp :0: connect: connection refused
8:29AM INF Inverter Model:
8:29AM INF Inverter Serial:
8:29AM INF Inverter Version:
8:29AM ERR Error reading holding registers: dial tcp :0: connect: connection refused
8:29AM ERR Attempting to reconnect
8:29AM ERR Error reading holding registers: dial tcp :0: connect: connection refused
8:29AM ERR Attempting to reconnect
```

When I do an nmap scan port 1502 is open and when using 'Simply Modbus TCP Client' on windows I can connect to the provided IP and port. I'm not sure if I'm doing anything wrong?

**Comment by 33Fraise33** [comment]
To add to this, the following tool is working but only outputs to PVoutput.org
https://github.com/Joozzt/Sunspec-solar-panels-monitor

**Comment by dave92082** [comment]
@33Fraise33 ,
Sorry for taking so long to get back to you. Judging by the log you posted, it looks as though you forgot to configure the exporter. The Inverter address and port liens should list the address and port of your inverter. Should look something like this if you set the config.yaml correctly:

```
6:50PM INF Starting SolarEdge-Exporter
6:50PM INF Configured Inverter Address: 192.168.1.213
6:50PM INF Configured Inverter Port: 502
6:50PM INF Configured Listen Address: 
6:50PM INF Configured Listen Port: 2112
6:50PM INF Inverter Model: SE5000
6:50PM INF Inverter Serial: 731DF6E3
6:50PM INF Inverter Version: 0003.2221
```

Make sure that you set up your config.yaml correctly or set the appropriate environment variables:

config.yaml that produced the above log example:
```yaml
SolarEdge:
  InverterAddress: "192.168.1.213"
  InverterPort: 502
Exporter:
  # Update Interval in seconds
  Interval: 5
Log:
  Debug: false
```

Further, this exporter searches in the following locations for the config.yaml:

* `.`  (the same folder where the binary is executed from)
* `/etc/solaredge-exporter/`
* `$HOME/.solaredge-exporter/`

**Comment by 33Fraise33** [comment]
hello,

Thank you so much for this, I have been looking for this for a very long time. I don't think at the time yml config was supported? 
Is the dockerfile still working, as I would like to run this as a service.

**Comment by dave92082** [comment]
The config.yaml is how the exporter was always configured (as well as
environment variables).

The docker file certainly still works.and that is how I run it. Take a look
at the config.go file in the repository to see the environment variable
mapping to config.yaml mapping.

**Comment by 33Fraise33** [comment]
hello thanks for your replies and this project, time to put this in ansible ;)
